--- 
automatic_scaling: 
  max_num_instances: 7
  min_num_instances: 1
entrypoint: "gunicorn -b :$PORT main:app"
env: flex
env_variables: 
  CLOUD_STORAGE_BUCKET: bangkit-face-exp
resources: 
  cpu: 2
  disk_size_gb: 10
  memory_gb: 2.3
  volumes: 
    - 
      name: ramdisk1
      size_gb: 0.5
      volume_type: tmpfs
runtime: custom
runtime_config: 
  python_version: 3
